## Where the samples will be written
save_data: data/JParaCrawl/run/example
## Where the vocab(s) will be written
src_vocab: data/JParaCrawl/run/example.vocab.src
tgt_vocab: data/JParaCrawl/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# OpenNMT-py/preprocess.py
data:
    corpus_1:
        path_src: data/JParaCrawl/en.txt.atok
        #path_tgt: data/JParaCrawl/ja.txt
        #path_tgt: data/JParaCrawl/ja-tok.txt
        path_tgt: data/JParaCrawl/ja.txt.atok
    valid: # sentencepieceでトークナイズしたkfttを使う
        path_src: data/JParaCrawl/kyoto-dev.en.atok
        path_tgt: data/JParaCrawl/kyoto-dev.ja.atok

# OpenNMT-py/train.py
save_model: data/JParaCrawl/run/model
layers: 6
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
heads: 8
encoder_type: transformer
decoder_type: transformer
position_encoding: 'true'
train_steps: 200000 # default
#train_steps: 15000
max_generator_batches: 2 # default
#max_generator_batches: 64
dropout: 0.1
#batch_size: 4096 # default
batch_size: 1024
batch_type: tokens
normalization: tokens
accum_count: 2
optim: adam
adam_beta2: 0.998
decay_method: noam
warmup_steps: 8000
learning_rate: 2
max_grad_norm: 0
param_init: 0
param_init_glorot: 'true'
label_smoothing: 0.1
valid_steps: 10000 # default
#valid_steps: 5000
#save_checkpoint_steps: 40000
save_checkpoint_steps: 10000 # default
world_size: 1
gpu_ranks: 0 